version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    networks:
      - host
  backend:
    build: "."
    container_name: backend
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - host

  docs:
    image: nginx
    container_name: docs
    volumes:
      - ./docs/index.html:/usr/share/nginx/html/index.html:ro
      - ./docs/openapi.yml:/usr/share/nginx/html/openapi.yml:ro
    ports:
      - 8081:80
    deploy:
      restart_policy:
        condition: on-failure

networks:
  host:
    driver: bridge
