version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    networks:
      - host
  backend:
    build: "."
    container_name: backend
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - host

networks:
  host:
    driver: bridge
