// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package search

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Query struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{0}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type Pin struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	MediaSource          string   `protobuf:"bytes,4,opt,name=MediaSource,proto3" json:"MediaSource,omitempty"`
	NumLikes             int64    `protobuf:"varint,5,opt,name=NumLikes,proto3" json:"NumLikes,omitempty"`
	Liked                bool     `protobuf:"varint,6,opt,name=Liked,proto3" json:"Liked,omitempty"`
	Author               int64    `protobuf:"varint,7,opt,name=Author,proto3" json:"Author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pin) Reset()         { *m = Pin{} }
func (m *Pin) String() string { return proto.CompactTextString(m) }
func (*Pin) ProtoMessage()    {}
func (*Pin) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1}
}

func (m *Pin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pin.Unmarshal(m, b)
}
func (m *Pin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pin.Marshal(b, m, deterministic)
}
func (m *Pin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pin.Merge(m, src)
}
func (m *Pin) XXX_Size() int {
	return xxx_messageInfo_Pin.Size(m)
}
func (m *Pin) XXX_DiscardUnknown() {
	xxx_messageInfo_Pin.DiscardUnknown(m)
}

var xxx_messageInfo_Pin proto.InternalMessageInfo

func (m *Pin) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pin) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Pin) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Pin) GetMediaSource() string {
	if m != nil {
		return m.MediaSource
	}
	return ""
}

func (m *Pin) GetNumLikes() int64 {
	if m != nil {
		return m.NumLikes
	}
	return 0
}

func (m *Pin) GetLiked() bool {
	if m != nil {
		return m.Liked
	}
	return false
}

func (m *Pin) GetAuthor() int64 {
	if m != nil {
		return m.Author
	}
	return 0
}

type Board struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Privacy              string   `protobuf:"bytes,4,opt,name=Privacy,proto3" json:"Privacy,omitempty"`
	UserId               int64    `protobuf:"varint,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Board) Reset()         { *m = Board{} }
func (m *Board) String() string { return proto.CompactTextString(m) }
func (*Board) ProtoMessage()    {}
func (*Board) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{2}
}

func (m *Board) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Board.Unmarshal(m, b)
}
func (m *Board) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Board.Marshal(b, m, deterministic)
}
func (m *Board) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Board.Merge(m, src)
}
func (m *Board) XXX_Size() int {
	return xxx_messageInfo_Board.Size(m)
}
func (m *Board) XXX_DiscardUnknown() {
	xxx_messageInfo_Board.DiscardUnknown(m)
}

var xxx_messageInfo_Board proto.InternalMessageInfo

func (m *Board) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Board) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Board) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Board) GetPrivacy() string {
	if m != nil {
		return m.Privacy
	}
	return ""
}

func (m *Board) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Profile struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	ProfileImage         string   `protobuf:"bytes,4,opt,name=ProfileImage,proto3" json:"ProfileImage,omitempty"`
	WebsiteUrl           string   `protobuf:"bytes,5,opt,name=WebsiteUrl,proto3" json:"WebsiteUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{3}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Profile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetProfileImage() string {
	if m != nil {
		return m.ProfileImage
	}
	return ""
}

func (m *Profile) GetWebsiteUrl() string {
	if m != nil {
		return m.WebsiteUrl
	}
	return ""
}

type QueryResult struct {
	Users                []*Profile `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	Boards               []*Board   `protobuf:"bytes,2,rep,name=Boards,proto3" json:"Boards,omitempty"`
	Pins                 []*Pin     `protobuf:"bytes,3,rep,name=Pins,proto3" json:"Pins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryResult) Reset()         { *m = QueryResult{} }
func (m *QueryResult) String() string { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()    {}
func (*QueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{4}
}

func (m *QueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResult.Unmarshal(m, b)
}
func (m *QueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResult.Marshal(b, m, deterministic)
}
func (m *QueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResult.Merge(m, src)
}
func (m *QueryResult) XXX_Size() int {
	return xxx_messageInfo_QueryResult.Size(m)
}
func (m *QueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResult proto.InternalMessageInfo

func (m *QueryResult) GetUsers() []*Profile {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *QueryResult) GetBoards() []*Board {
	if m != nil {
		return m.Boards
	}
	return nil
}

func (m *QueryResult) GetPins() []*Pin {
	if m != nil {
		return m.Pins
	}
	return nil
}

func init() {
	proto.RegisterType((*Query)(nil), "search.Query")
	proto.RegisterType((*Pin)(nil), "search.Pin")
	proto.RegisterType((*Board)(nil), "search.Board")
	proto.RegisterType((*Profile)(nil), "search.Profile")
	proto.RegisterType((*QueryResult)(nil), "search.QueryResult")
}

func init() {
	proto.RegisterFile("search.proto", fileDescriptor_453745cff914010e)
}

var fileDescriptor_453745cff914010e = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0xea, 0xd3, 0x30,
	0x14, 0xc7, 0x6d, 0xbb, 0xf6, 0xb7, 0x9d, 0x4e, 0x85, 0x28, 0x12, 0x06, 0x6a, 0x29, 0x0c, 0x06,
	0xc2, 0x84, 0x79, 0xb9, 0x2b, 0x87, 0x22, 0x05, 0x1d, 0x33, 0x73, 0x08, 0xde, 0x75, 0x6d, 0xdc,
	0x82, 0x5d, 0x3b, 0x93, 0x56, 0x18, 0x08, 0x3e, 0x81, 0x0f, 0xe4, 0xdb, 0x49, 0x4e, 0xd2, 0xda,
	0xb1, 0x1b, 0xef, 0xf2, 0xfd, 0xd3, 0x73, 0x3e, 0xa4, 0x81, 0xb1, 0xe2, 0xa9, 0xcc, 0x8e, 0xf3,
	0xb3, 0xac, 0xea, 0x8a, 0x04, 0x46, 0xc5, 0x4f, 0xc1, 0xff, 0xd8, 0x70, 0x79, 0x21, 0x8f, 0xc1,
	0xff, 0xae, 0x0f, 0xd4, 0x89, 0x9c, 0xd9, 0x88, 0x19, 0x11, 0xff, 0x71, 0xc0, 0xdb, 0x88, 0x92,
	0x3c, 0x00, 0x37, 0xc9, 0x31, 0xf2, 0x98, 0x9b, 0xe4, 0xba, 0xfd, 0x49, 0xd4, 0x05, 0xa7, 0xae,
	0x69, 0xa3, 0x20, 0x11, 0x84, 0x6f, 0xb8, 0xca, 0xa4, 0x38, 0xd7, 0xa2, 0x2a, 0xa9, 0x87, 0x59,
	0xdf, 0xd2, 0x8d, 0x0f, 0x3c, 0x17, 0xe9, 0xb6, 0x6a, 0x64, 0xc6, 0xe9, 0xc0, 0x34, 0x7a, 0x16,
	0x99, 0xc0, 0x70, 0xdd, 0x9c, 0xde, 0x8b, 0x6f, 0x5c, 0x51, 0x1f, 0xf7, 0x75, 0x5a, 0x6f, 0xd5,
	0x87, 0x9c, 0x06, 0x91, 0x33, 0x1b, 0x32, 0x23, 0xc8, 0x13, 0x08, 0x5e, 0x37, 0xf5, 0xb1, 0x92,
	0xf4, 0x0e, 0xfb, 0x56, 0xc5, 0xbf, 0xc0, 0x5f, 0x55, 0xa9, 0xcc, 0x6f, 0xe0, 0x09, 0x0c, 0xd6,
	0xe9, 0xa9, 0x65, 0xc7, 0xf3, 0x7f, 0xa0, 0x53, 0xb8, 0xdb, 0x48, 0xf1, 0x23, 0xcd, 0x2e, 0x16,
	0xbb, 0x95, 0x1a, 0x60, 0xa7, 0xb8, 0x4c, 0x72, 0x0b, 0x6c, 0x55, 0xfc, 0xdb, 0xd1, 0x9f, 0x54,
	0x5f, 0x45, 0xc1, 0x6f, 0x18, 0x26, 0x30, 0xd4, 0xad, 0xf2, 0x1f, 0x47, 0xa7, 0x3b, 0x3e, 0xaf,
	0xc7, 0x17, 0xc3, 0xd8, 0x8e, 0x4a, 0x4e, 0xe9, 0xa1, 0xbd, 0xb9, 0x2b, 0x8f, 0x3c, 0x03, 0xf8,
	0xcc, 0xf7, 0x4a, 0xd4, 0x7c, 0x27, 0x0b, 0x64, 0x19, 0xb1, 0x9e, 0x13, 0xff, 0x84, 0x10, 0xff,
	0x35, 0xe3, 0xaa, 0x29, 0x6a, 0x32, 0x05, 0x5f, 0xaf, 0x54, 0xd4, 0x89, 0xbc, 0x59, 0xb8, 0x78,
	0x38, 0xb7, 0x0f, 0xc4, 0xce, 0x64, 0x26, 0x25, 0x53, 0x08, 0xf0, 0x1a, 0x15, 0x75, 0xb1, 0x77,
	0xbf, 0xed, 0xa1, 0xcb, 0x6c, 0x48, 0x9e, 0xc3, 0x60, 0x23, 0x4a, 0x45, 0x3d, 0x2c, 0x85, 0xdd,
	0x30, 0x51, 0x32, 0x0c, 0x16, 0x4b, 0x18, 0x6f, 0xd1, 0x7b, 0x5b, 0x1e, 0x44, 0xc9, 0xc9, 0x0b,
	0xf0, 0xde, 0xf1, 0x9a, 0x74, 0xe3, 0x10, 0x6d, 0xf2, 0xe8, 0x4a, 0x1a, 0xd2, 0xf8, 0xde, 0x2a,
	0xfc, 0x32, 0x9a, 0xbf, 0x5c, 0x9a, 0x68, 0x1f, 0xe0, 0x13, 0x7e, 0xf5, 0x37, 0x00, 0x00, 0xff,
	0xff, 0xd5, 0x2a, 0xc7, 0x6c, 0xd2, 0x02, 0x00, 0x00,
}
