// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD6aedbb7DecodeGithubComGoParkMailRu20231PracticalDevInternalModels(in *jlexer.Lexer, out *Pin) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "title":
			out.Title = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "media_source":
			out.MediaSource = string(in.String())
		case "media_source_color":
			out.MediaSourceColor = string(in.String())
		case "n_likes":
			out.NumLikes = int(in.Int())
		case "liked":
			out.Liked = bool(in.Bool())
		case "author":
			easyjsonD6aedbb7DecodeGithubComGoParkMailRu20231PracticalDevInternalModels1(in, &out.Author)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD6aedbb7EncodeGithubComGoParkMailRu20231PracticalDevInternalModels(out *jwriter.Writer, in Pin) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"media_source\":"
		out.RawString(prefix)
		out.String(string(in.MediaSource))
	}
	{
		const prefix string = ",\"media_source_color\":"
		out.RawString(prefix)
		out.String(string(in.MediaSourceColor))
	}
	{
		const prefix string = ",\"n_likes\":"
		out.RawString(prefix)
		out.Int(int(in.NumLikes))
	}
	{
		const prefix string = ",\"liked\":"
		out.RawString(prefix)
		out.Bool(bool(in.Liked))
	}
	{
		const prefix string = ",\"author\":"
		out.RawString(prefix)
		easyjsonD6aedbb7EncodeGithubComGoParkMailRu20231PracticalDevInternalModels1(out, in.Author)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Pin) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD6aedbb7EncodeGithubComGoParkMailRu20231PracticalDevInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Pin) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD6aedbb7EncodeGithubComGoParkMailRu20231PracticalDevInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Pin) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD6aedbb7DecodeGithubComGoParkMailRu20231PracticalDevInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Pin) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD6aedbb7DecodeGithubComGoParkMailRu20231PracticalDevInternalModels(l, v)
}
func easyjsonD6aedbb7DecodeGithubComGoParkMailRu20231PracticalDevInternalModels1(in *jlexer.Lexer, out *Profile) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int(in.Int())
		case "username":
			out.Username = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "profile_image":
			out.ProfileImage = string(in.String())
		case "website_url":
			out.WebsiteUrl = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD6aedbb7EncodeGithubComGoParkMailRu20231PracticalDevInternalModels1(out *jwriter.Writer, in Profile) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"profile_image\":"
		out.RawString(prefix)
		out.String(string(in.ProfileImage))
	}
	{
		const prefix string = ",\"website_url\":"
		out.RawString(prefix)
		out.String(string(in.WebsiteUrl))
	}
	out.RawByte('}')
}
