// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	HashedPassword       string   `protobuf:"bytes,4,opt,name=HashedPassword,proto3" json:"HashedPassword,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	ProfileImage         string   `protobuf:"bytes,6,opt,name=ProfileImage,proto3" json:"ProfileImage,omitempty"`
	WebsiteUrl           string   `protobuf:"bytes,7,opt,name=WebsiteUrl,proto3" json:"WebsiteUrl,omitempty"`
	AccountType          string   `protobuf:"bytes,8,opt,name=AccountType,proto3" json:"AccountType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetHashedPassword() string {
	if m != nil {
		return m.HashedPassword
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetProfileImage() string {
	if m != nil {
		return m.ProfileImage
	}
	return ""
}

func (m *User) GetWebsiteUrl() string {
	if m != nil {
		return m.WebsiteUrl
	}
	return ""
}

func (m *User) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

type LoginParams struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginParams) Reset()         { *m = LoginParams{} }
func (m *LoginParams) String() string { return proto.CompactTextString(m) }
func (*LoginParams) ProtoMessage()    {}
func (*LoginParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *LoginParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginParams.Unmarshal(m, b)
}
func (m *LoginParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginParams.Marshal(b, m, deterministic)
}
func (m *LoginParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginParams.Merge(m, src)
}
func (m *LoginParams) XXX_Size() int {
	return xxx_messageInfo_LoginParams.Size(m)
}
func (m *LoginParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginParams.DiscardUnknown(m)
}

var xxx_messageInfo_LoginParams proto.InternalMessageInfo

func (m *LoginParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterParams struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterParams) Reset()         { *m = RegisterParams{} }
func (m *RegisterParams) String() string { return proto.CompactTextString(m) }
func (*RegisterParams) ProtoMessage()    {}
func (*RegisterParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *RegisterParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterParams.Unmarshal(m, b)
}
func (m *RegisterParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterParams.Marshal(b, m, deterministic)
}
func (m *RegisterParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterParams.Merge(m, src)
}
func (m *RegisterParams) XXX_Size() int {
	return xxx_messageInfo_RegisterParams.Size(m)
}
func (m *RegisterParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterParams.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterParams proto.InternalMessageInfo

func (m *RegisterParams) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterParams) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterParams) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SessionParams struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	LivingTime           int64    `protobuf:"varint,2,opt,name=LivingTime,proto3" json:"LivingTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionParams) Reset()         { *m = SessionParams{} }
func (m *SessionParams) String() string { return proto.CompactTextString(m) }
func (*SessionParams) ProtoMessage()    {}
func (*SessionParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *SessionParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionParams.Unmarshal(m, b)
}
func (m *SessionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionParams.Marshal(b, m, deterministic)
}
func (m *SessionParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionParams.Merge(m, src)
}
func (m *SessionParams) XXX_Size() int {
	return xxx_messageInfo_SessionParams.Size(m)
}
func (m *SessionParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionParams.DiscardUnknown(m)
}

var xxx_messageInfo_SessionParams proto.InternalMessageInfo

func (m *SessionParams) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SessionParams) GetLivingTime() int64 {
	if m != nil {
		return m.LivingTime
	}
	return 0
}

type SessionParamsWithUser struct {
	Params               *SessionParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	User                 *User          `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SessionParamsWithUser) Reset()         { *m = SessionParamsWithUser{} }
func (m *SessionParamsWithUser) String() string { return proto.CompactTextString(m) }
func (*SessionParamsWithUser) ProtoMessage()    {}
func (*SessionParamsWithUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *SessionParamsWithUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionParamsWithUser.Unmarshal(m, b)
}
func (m *SessionParamsWithUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionParamsWithUser.Marshal(b, m, deterministic)
}
func (m *SessionParamsWithUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionParamsWithUser.Merge(m, src)
}
func (m *SessionParamsWithUser) XXX_Size() int {
	return xxx_messageInfo_SessionParamsWithUser.Size(m)
}
func (m *SessionParamsWithUser) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionParamsWithUser.DiscardUnknown(m)
}

var xxx_messageInfo_SessionParamsWithUser proto.InternalMessageInfo

func (m *SessionParamsWithUser) GetParams() *SessionParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *SessionParamsWithUser) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SessionCheckParams struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SessionId            string   `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionCheckParams) Reset()         { *m = SessionCheckParams{} }
func (m *SessionCheckParams) String() string { return proto.CompactTextString(m) }
func (*SessionCheckParams) ProtoMessage()    {}
func (*SessionCheckParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *SessionCheckParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionCheckParams.Unmarshal(m, b)
}
func (m *SessionCheckParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionCheckParams.Marshal(b, m, deterministic)
}
func (m *SessionCheckParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionCheckParams.Merge(m, src)
}
func (m *SessionCheckParams) XXX_Size() int {
	return xxx_messageInfo_SessionCheckParams.Size(m)
}
func (m *SessionCheckParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionCheckParams.DiscardUnknown(m)
}

var xxx_messageInfo_SessionCheckParams proto.InternalMessageInfo

func (m *SessionCheckParams) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SessionCheckParams) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type Nothing struct {
	Dummy                bool     `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

func (m *Nothing) GetDummy() bool {
	if m != nil {
		return m.Dummy
	}
	return false
}

type Session struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserEmail            string   `protobuf:"bytes,2,opt,name=UserEmail,proto3" json:"UserEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Session) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

type SessionSetParams struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Session              *Session `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Experation           int64    `protobuf:"varint,3,opt,name=Experation,proto3" json:"Experation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionSetParams) Reset()         { *m = SessionSetParams{} }
func (m *SessionSetParams) String() string { return proto.CompactTextString(m) }
func (*SessionSetParams) ProtoMessage()    {}
func (*SessionSetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *SessionSetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionSetParams.Unmarshal(m, b)
}
func (m *SessionSetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionSetParams.Marshal(b, m, deterministic)
}
func (m *SessionSetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionSetParams.Merge(m, src)
}
func (m *SessionSetParams) XXX_Size() int {
	return xxx_messageInfo_SessionSetParams.Size(m)
}
func (m *SessionSetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionSetParams.DiscardUnknown(m)
}

var xxx_messageInfo_SessionSetParams proto.InternalMessageInfo

func (m *SessionSetParams) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SessionSetParams) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *SessionSetParams) GetExperation() int64 {
	if m != nil {
		return m.Experation
	}
	return 0
}

type UserId struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "auth.User")
	proto.RegisterType((*LoginParams)(nil), "auth.LoginParams")
	proto.RegisterType((*RegisterParams)(nil), "auth.RegisterParams")
	proto.RegisterType((*SessionParams)(nil), "auth.SessionParams")
	proto.RegisterType((*SessionParamsWithUser)(nil), "auth.SessionParamsWithUser")
	proto.RegisterType((*SessionCheckParams)(nil), "auth.SessionCheckParams")
	proto.RegisterType((*Nothing)(nil), "auth.Nothing")
	proto.RegisterType((*Session)(nil), "auth.Session")
	proto.RegisterType((*SessionSetParams)(nil), "auth.SessionSetParams")
	proto.RegisterType((*UserId)(nil), "auth.UserId")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6a, 0xdb, 0x4c,
	0x10, 0xb5, 0x2d, 0xc5, 0x3f, 0xe3, 0xd8, 0x7c, 0xdf, 0xf4, 0x07, 0x61, 0x4a, 0x6a, 0xf6, 0xa2,
	0x0d, 0x04, 0x1c, 0x70, 0xe8, 0x4d, 0x7b, 0x11, 0xd2, 0xda, 0x50, 0x97, 0x10, 0x8c, 0x6c, 0x13,
	0xe8, 0x9d, 0x62, 0x4f, 0xac, 0x25, 0x96, 0xe4, 0xee, 0xae, 0xdb, 0xe6, 0x41, 0xfa, 0x92, 0x7d,
	0x8a, 0xb2, 0xab, 0x95, 0x25, 0xb9, 0xe4, 0xa6, 0x77, 0x9a, 0x33, 0x3f, 0x67, 0xe6, 0x9c, 0x45,
	0x00, 0xc1, 0x4e, 0x85, 0x83, 0xad, 0x48, 0x54, 0x82, 0xae, 0xfe, 0x66, 0xbf, 0xab, 0xe0, 0x2e,
	0x24, 0x09, 0xec, 0x42, 0x6d, 0x32, 0xf2, 0xaa, 0xfd, 0xea, 0xa9, 0xe3, 0xd7, 0x26, 0x23, 0xec,
	0x41, 0x53, 0xe3, 0x71, 0x10, 0x91, 0x57, 0xeb, 0x57, 0x4f, 0x5b, 0xfe, 0x3e, 0xc6, 0xe7, 0x70,
	0x34, 0x8e, 0x02, 0xbe, 0xf1, 0x1c, 0x93, 0x48, 0x03, 0x7c, 0x03, 0xdd, 0xcf, 0x81, 0x0c, 0x69,
	0x35, 0x0d, 0xa4, 0xfc, 0x91, 0x88, 0x95, 0xe7, 0x9a, 0xf4, 0x01, 0x8a, 0x08, 0xee, 0x8d, 0x9e,
	0x7a, 0x64, 0xb2, 0xe6, 0x1b, 0x19, 0x1c, 0x4f, 0x45, 0x72, 0xcf, 0x37, 0x34, 0x89, 0x82, 0x35,
	0x79, 0x75, 0x93, 0x2b, 0x61, 0x78, 0x02, 0x70, 0x4b, 0x77, 0x92, 0x2b, 0x5a, 0x88, 0x8d, 0xd7,
	0x30, 0x15, 0x05, 0x04, 0xfb, 0xd0, 0xbe, 0x5a, 0x2e, 0x93, 0x5d, 0xac, 0xe6, 0x8f, 0x5b, 0xf2,
	0x9a, 0xa6, 0xa0, 0x08, 0xb1, 0x4b, 0x68, 0x5f, 0x27, 0x6b, 0x1e, 0x4f, 0x03, 0x11, 0x44, 0x32,
	0x3f, 0xa3, 0x5a, 0x3c, 0xa3, 0x07, 0xcd, 0xfd, 0x01, 0xf6, 0xf0, 0x2c, 0x66, 0x02, 0xba, 0x3e,
	0xad, 0xb9, 0x54, 0x24, 0xfe, 0x75, 0x46, 0x49, 0x58, 0xe7, 0x40, 0xd8, 0x4c, 0x1a, 0x37, 0x97,
	0x86, 0x8d, 0xa1, 0x33, 0x23, 0x29, 0x79, 0x52, 0x58, 0x7b, 0x9e, 0x3c, 0x50, 0x9c, 0x51, 0x9a,
	0x40, 0xab, 0x73, 0xcd, 0xbf, 0xf3, 0x78, 0x3d, 0xe7, 0xd6, 0x31, 0xc7, 0x2f, 0x20, 0x6c, 0x05,
	0x2f, 0x4a, 0x63, 0x6e, 0xb9, 0x0a, 0x8d, 0xf1, 0x67, 0x50, 0xdf, 0x1a, 0xc4, 0xcc, 0x6b, 0x0f,
	0x9f, 0x0d, 0xcc, 0x23, 0x29, 0x15, 0xfb, 0xb6, 0x04, 0x4f, 0xc0, 0xdd, 0x49, 0x12, 0x66, 0x7e,
	0x7b, 0x08, 0x69, 0xa9, 0x1e, 0xe3, 0x1b, 0x9c, 0x7d, 0x01, 0xb4, 0x8d, 0x9f, 0x42, 0x5a, 0x3e,
	0xd8, 0x8d, 0x5f, 0x42, 0x5d, 0x67, 0x27, 0x2b, 0xbb, 0xb2, 0x8d, 0xf0, 0x15, 0xb4, 0x64, 0x5a,
	0x3d, 0xc9, 0x74, 0xca, 0x01, 0xf6, 0x1a, 0x1a, 0x37, 0x89, 0x0a, 0x79, 0xbc, 0xd6, 0x27, 0xaf,
	0x76, 0x51, 0xf4, 0x68, 0xfa, 0x9b, 0x7e, 0x1a, 0xb0, 0x4b, 0x68, 0x58, 0x32, 0xcd, 0xb0, 0xc8,
	0x19, 0x1c, 0xdf, 0x46, 0x9a, 0x41, 0x7f, 0xa5, 0x16, 0x59, 0x86, 0x3d, 0xc0, 0xbe, 0xc1, 0x7f,
	0x76, 0xc0, 0x8c, 0x54, 0xae, 0xae, 0x2a, 0xaa, 0x6b, 0x02, 0x7c, 0x0b, 0x0d, 0xbb, 0x98, 0x3d,
	0xbd, 0x53, 0x52, 0xc9, 0xcf, 0xb2, 0xda, 0x86, 0xf1, 0xcf, 0x2d, 0x89, 0x40, 0xe9, 0x5a, 0x27,
	0xb5, 0x21, 0x47, 0x58, 0x3f, 0x5b, 0xf4, 0xa9, 0x95, 0x87, 0xbf, 0x6a, 0xd0, 0xb9, 0xda, 0xa9,
	0x90, 0xe2, 0x7b, 0xbe, 0x0c, 0x54, 0x22, 0xf0, 0x1c, 0x8e, 0x53, 0x40, 0x69, 0x80, 0xf0, 0xff,
	0x94, 0xbb, 0xf0, 0x94, 0x7b, 0x05, 0x27, 0x58, 0x05, 0xcf, 0xa0, 0x99, 0x3d, 0x53, 0x2c, 0x64,
	0x7a, 0x7f, 0x37, 0xb2, 0x0a, 0xbe, 0x03, 0x98, 0x91, 0xda, 0x0b, 0x59, 0xba, 0x6b, 0x2f, 0x4b,
	0xcf, 0xde, 0x6b, 0x0d, 0x61, 0x15, 0xbc, 0x80, 0x96, 0xb1, 0x58, 0x6f, 0x86, 0x5e, 0xa9, 0xab,
	0x60, 0xfd, 0xc1, 0x62, 0xef, 0xa1, 0x33, 0xa2, 0x0d, 0x29, 0xca, 0xe8, 0x9e, 0x6e, 0x3c, 0x24,
	0xfc, 0xd8, 0xfa, 0xda, 0x18, 0x9c, 0x7f, 0xd0, 0xe0, 0x5d, 0xdd, 0xfc, 0xc1, 0x2e, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xc3, 0x3a, 0x05, 0x42, 0xcf, 0x04, 0x00, 0x00,
}
