// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: images.proto

package images

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageUploaderClient is the client API for ImageUploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageUploaderClient interface {
	UploadImage(ctx context.Context, in *Image, opts ...grpc.CallOption) (*Url, error)
}

type imageUploaderClient struct {
	cc grpc.ClientConnInterface
}

func NewImageUploaderClient(cc grpc.ClientConnInterface) ImageUploaderClient {
	return &imageUploaderClient{cc}
}

func (c *imageUploaderClient) UploadImage(ctx context.Context, in *Image, opts ...grpc.CallOption) (*Url, error) {
	out := new(Url)
	err := c.cc.Invoke(ctx, "/images.ImageUploader/UploadImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageUploaderServer is the server API for ImageUploader service.
// All implementations must embed UnimplementedImageUploaderServer
// for forward compatibility
type ImageUploaderServer interface {
	UploadImage(context.Context, *Image) (*Url, error)
	mustEmbedUnimplementedImageUploaderServer()
}

// UnimplementedImageUploaderServer must be embedded to have forward compatible implementations.
type UnimplementedImageUploaderServer struct {
}

func (UnimplementedImageUploaderServer) UploadImage(context.Context, *Image) (*Url, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedImageUploaderServer) mustEmbedUnimplementedImageUploaderServer() {}

// UnsafeImageUploaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageUploaderServer will
// result in compilation errors.
type UnsafeImageUploaderServer interface {
	mustEmbedUnimplementedImageUploaderServer()
}

func RegisterImageUploaderServer(s grpc.ServiceRegistrar, srv ImageUploaderServer) {
	s.RegisterService(&ImageUploader_ServiceDesc, srv)
}

func _ImageUploader_UploadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Image)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageUploaderServer).UploadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/images.ImageUploader/UploadImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageUploaderServer).UploadImage(ctx, req.(*Image))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageUploader_ServiceDesc is the grpc.ServiceDesc for ImageUploader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageUploader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "images.ImageUploader",
	HandlerType: (*ImageUploaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadImage",
			Handler:    _ImageUploader_UploadImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "images.proto",
}
