{
 "title": "Auth service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "auth_durations_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth success hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "auth_success_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth total hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "auth_total_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth error hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "auth_errors_hits", "legendFormat": "__auto" }
   ]
  }
 ]
}