{
 "title": "Images service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "images_durations_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Images error hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "images_errors_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Images total hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "images_total_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Images success hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "images_success_hits", "legendFormat": "__auto" }
   ]
  }
 ]
}