{
 "title": "pickpin",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pickpin_durations_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "pickpin_errors_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pickpin_total_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Success hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "pickpin_success_hits", "legendFormat": "__auto" },
    { "expr": "pickpin_errors_hits", "legendFormat": "__auto" },
    { "expr": "pickpin_total_hits", "legendFormat": "__auto" },
    {}
   ]
  }
 ]
}