{
 "title": "Search service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "search_durations_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Success hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "search_success_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "search_total_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "search_error_hits", "legendFormat": "__auto" }
   ]
  }
 ]
}