{
 "title": "Shortener service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(shortener_durations_sum[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Shortener success hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "shortener_success_hits", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Shortener total hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "shortener_total_hits", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Shortener error hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "shortener_errors_hits", "legendFormat": "{{path}}" }
   ]
  }
 ]
}