global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: pickpin
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'backend:9001' ]

  - job_name: images
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'images:9002' ]

  - job_name: auth
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ 'auth:9003' ]
