name: Backend CI

on:
  push:

env:
  DOCKER_BUILDKIT: "1"

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: '-w'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
            commit_message: Apply formatting changes
            branch: ${{ github.head_ref }}

  Lint:
    runs-on: ubuntu-latest
    needs: [Format]
    steps:
      - uses: actions/checkout@v3

      - name: Run lint
        run: make lint

  Unit-test:
    runs-on: ubuntu-latest
    needs: [Lint]
    steps:
      - uses: actions/checkout@v3

      - name: Start DB
        run: make db && ./scripts/check_db_available.sh

      - name: Populate DB with test data
        run: ././scripts/populate_db.sh
        
      - name: Run unit tests
        run: make unit-test

      - name: Get coverage
        run: make print-coverage

  Deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [Lint, Unit-test]
    steps:
      - uses: actions/checkout@v3

      - name: Login to YC Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build docker imaged
        run: make build-images

      - name: Push docker imaged
        run: make push-images
      
      - name: Run backend # даже интересно, будет ли это работать
        uses: appleboy/ssh-action@master
        with:
          host: pickpin.ru
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd 2023_Practical_Dev/backend
            make pull-images
            make deploy
            make metrics
